apiVersion: apps/v1
kind: Deployment
metadata:
  name: quota-deployment
  namespace: team-1
  labels:
    app: quota
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quota
  template:
    metadata:
      labels:
        app: quota
    spec:
      imagePullSecrets:
        - name: harbour-pull-secret1
      containers:
        - name: quota
          imagePullPolicy: Always
          image: harbor.infra.cluster.ionos.com/paasis-dev/wb-group2/team-2:latest
          ports:
            - containerPort: 8080