apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-2
  labels:
    app: quota
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quota
  template:
    metadata:
      labels:
        app: quota
    spec:
      containers:
        - name: quota
          image: harbor.infra.cluster.ionos.com/paasis-dev/wb-group2/team-1:latest
          ports:
            - containerPort: 80
